sonar.projectKey=Serpacr_InforRush
sonar.projectName=InfoRush
sonar.organization=serpacr

sonar.sourceEncoding=UTF-8

sonar.sources=inforush/backend/src/main/java,inforush/frontend/src
sonar.tests=inforush/backend/src/test/java

sonar.java.binaries=inforush/backend/target/classes
sonar.java.test.binaries=inforush/backend/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=inforush/backend/target/site/jacoco/jacoco.xml

sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/*.css
