services:
  database:
    image: postgres:16-alpine
    container_name: inforush-db
    environment:
      POSTGRES_DB: inforush
      POSTGRES_USER: inforush
      POSTGRES_PASSWORD: inforush123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inforush"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - inforush-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: inforush-backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DATABASE_URL: jdbc:postgresql://database:5432/inforush
      DB_USER: inforush
      DB_PASSWORD: inforush123
      JWT_SECRET: inforush-super-secret-jwt-key-mude-em-producao-2024
      PORT: 8080
      FRONTEND_URL: http://localhost:5173
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - inforush-net
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: inforush-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - inforush-net
    restart: on-failure

volumes:
  postgres_data:

networks:
  inforush-net:
    driver: bridge
